version: "3.9"

services:
  fastapi-backend:
    build: ./fastapi-auth
    ports:
      - "8000:8000"
  sveltekit-frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - ./frontend/.env